### ISSUE TITLE
Markdown to structure the command.

### ISSUE THREAD

**Issue by Akshaykumar05** [Akshaykumar05/community-forum#1]
Use markdown to structure the command in readme.md file for all the used command. 

### Example: 
* EMAIL_HOST = "smtp-relay.sendinblue.com" EMAIL_HOST_USER = "your_registration@email.com" EMAIL_PORT = 587
* su zulip -c '/home/zulip/deployments/current/scripts/restart-server'

**Comment by AnkitV1001** [comment]
Please assign me this task, I would like to work on it.

**Comment by Akshaykumar05** [comment]
Okey, I'm assigning this task to you.
